# Generated by Django 2.2.7 on 2019-12-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191203_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marriage',
            options={'verbose_name_plural': 'marriages'},
        ),
        migrations.AlterField(
            model_name='marriage',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
